#159989012 Implement user signup functionality
andela/fargo-ah-client pull request #31
Opened 2018-09-13 18:29 UTC by Oloyedesinmiloluwa

###What does this PR do?
Has user sign up implementation
###Description of Task to be completed?
    - enable user registration
    - display error details
    - add unit and integration tests
###How should this be manually tested?
- `git clone the repo`
- `npm install`
- `npm run start` the start script
- Go to '/login' path and click on `register`
- Enter requested detail.
What are the relevant pivotal tracker stories?
 [#159989014](https://www.pivotaltracker.com/story/show/159989012)
Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/32905583/45507913-445bbc80-b78b-11e8-8dc7-b817d56c3792.png)

2018-09-20 08:51 UTC, veeqtor commented on src/redux/actions/signupAction.js
> +    localStorage.setItem('token', res.data.user.token);
Nice work sinmi, However, we already have a name for setting the token on local storage, I suggest you go with the agreed name for consistency.

2018-09-20 08:54 UTC, veeqtor commented on src/styles/font.scss
> +$description-font: "Abel", sans-serif;
This file is redundant, We already have a `fonts` file, You can go ahead and remove it.

2018-09-20 08:59 UTC, veeqtor commented on src/styles/loginCard.scss
> +@import "./colours";
These can also be removed, since we are already importing them in the `index.scss`

2018-09-20 11:08 UTC, veeqtor approved these changes

2018-09-20 11:20 UTC, Lumexralph approved these changes

2018-09-20 11:26 UTC, Lumexralph requested changes
Please kindly check the format your PR message, the headers should be bolder than the body of the text.

2018-09-20 13:47 UTC, Lumexralph approved these changes

2018-09-24 14:31 UTC, anuonifade approved these changes
LGTM

2018-09-24 14:32 UTC, merged