Ch 159989010 setup sass
andela/fargo-ah-client pull request #6
Opened 2018-08-30 09:33 UTC by klevamane

#### What does this PR do?
Setup sass preprocessing on the application
#### Description of Task to be completed?
- add sass-loader to webpack
- configure webpack to test for .scss
#### How should this be manually tested?
In ComandLine:
- `git clone https://github.com/andela/fargo-ah-client.git Authors-Haven-Client`
- `npm install`
- `add sass or css styles to style.scss file in /src/scss/style.scss`
-  `import the style.scss file in the desired component .js file`
- `npm run start` the start script

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/#159989010

2018-08-30 10:53 UTC, Oloyedesinmiloluwa commented on webpack.config.js
> +            loader: 'sass-loader', // compiles Sass to CSS
please re-write this comment to follow Airbnb comment style https://github.com/airbnb/javascript#comments

2018-08-30 11:02 UTC, Oloyedesinmiloluwa reviewed
Please write a minimalistic code in the `.scss` file to show it is actually bundling

2018-08-30 14:27 UTC, anneKay requested changes
Please use the requested format for naming pull request.

2018-09-03 10:49 UTC, anneKay approved these changes

2018-09-03 11:43 UTC, Oloyedesinmiloluwa approved these changes
Alright, I think this is ok to be merged

2018-09-06 12:37 UTC, anuonifade approved these changes
LGTM

2018-09-06 12:38 UTC, merged